[project]
name = "agentic-systems-with-langgraph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=1.2.10",
    "langchain-community>=0.4.1",
    "langchain-core>=1.2.16",
    "langchain-groq>=1.1.2",
    "langchainhub>=0.1.21",
    "langgraph>=1.0.10",
    "python-dotenv>=1.2.1",
    "tavily-python>=0.7.23",
]
