from langgraph.graph import StateGraph,MessagesState,START,END


def mock_llm(state:MessagesState):
    return {"message":[{"role":"ai","content":"hello world"}]}


graph= StateGraph(MessagesState)

graph.add_node(mock_llm)
graph.add_edge(START,"mock_llm")
graph.add_edge("mock_llm",END)

graph.compile()

graph.invoke({"messages": [{"role": "user", "content": "hi!"}]})



from typing import TypedDict, List, Optional

# Define the structure of a single shopping item
class Shoping(TypedDict):
    item: str
    quantity: int
    bought: Optional[bool]  # Can be True, False, or None

# Define the structure of the shopping list
class ShopingList(TypedDict):
    shopings: List[Shoping]

# Initialize a shopping list
shoping_list: ShopingList = {
    "shopings": [
        {"item": "apple", "quantity": 3, "bought": None},
        {"item": "banana", "quantity": 2, "bought": None},
        {"item": "orange", "quantity": 1, "bought": None},
    ]
}

# Function to print the shopping list
def print_shoping_list(shoping_list: ShopingList):
    for shoping in shoping_list["shopings"]:
        status = "✅" if shoping["bought"] else "❌" if shoping["bought"] == False else "⏳"
        print(f"{status} {shoping['quantity']} x {shoping['item']}")

# Function to update the shopping list
def update_shoping_list(shoping_list: ShopingList, item: str, bought: bool):
    for shoping in shoping_list["shopings"]:
        if shoping["item"] == item:
            shoping["bought"] = bought
            break

# Add a new shopping item to the list
def add_shoping_item(shoping_list: ShopingList, item: str, quantity: int):
    shoping_list["shopings"].append({"item": item, "quantity": quantity, "bought": None})

# Example Usage
print("Initial Shopping List:")
print_shoping_list(shoping_list)

print("\nUpdating 'apple' to bought...")
update_shoping_list(shoping_list, "apple", True)
print_shoping_list(shoping_list)

print("\nAdding 'grapes' to the shopping list...")
add_shoping_item(shoping_list, "grapes", 4)
print_shoping_list(shoping_list)



# class TravelPlan(TypedDict):
#     user_request:str
#     user_id:str

#     search_results: Optional[List[str]]
#     itinerary: Optional[List[str]]

#     reviews: Optional[List[str]]


from typing import TypedDict, Optional, List, Dict
from langgraph.types import Command   # ← This is the magic for routing

class TravelPlan(TypedDict):
    # === Raw input that never changes ===
    user_request: str          # "Help me plan a 5-day trip to Paris in June"
    user_id: str               # For loading preferences, history, etc.

    # === Parsed once and stored (cheap to parse, used by many nodes) ===
    destination: Optional[str] = None
    dates: Optional[Dict[str, str]] = None
    budget: Optional[int] = None        # ← Added because we check it!

    # === Expensive stuff from tools ===
    search_results: Optional[List[str]] = None

    # === Generated by the agent ===
    itinerary: Optional[List[str]] = None
    draft_review: Optional[List[str]] = None


# ==================== YOUR FIRST NODE ====================
def classify_travel_request(state: TravelPlan) -> Command:
    """Node 1: Parse the request and decide where to go next"""
    
    print(f"Classifying request for user {state['user_id']}")

    # ============= REAL LLM CALL (replace this part) =============
    # In production you would do:
    # from langchain_core.prompts import ChatPromptTemplate
    # llm = ...your_model...
    # structured_llm = llm.with_structured_output(TravelDetails)  # Pydantic model
    # result = structured_llm.invoke(state["user_request"])
    
    # For now, we simulate the LLM output:
    parsed = {
        "destination": "Paris",
        "dates": {"start": "2025-06-01", "end": "2025-06-05"},
        "budget": 2500
    }
    # =============================================================

    # Decide routing (exactly like the official email agent!)
    if not parsed["destination"] or not parsed["dates"]:
        next_node = "human_review"      # missing info → ask user
    else:
        next_node = "search"            # ready to search flights/hotels

    return Command(
        update={
            "destination": parsed["destination"],
            "dates": parsed["dates"],
            "budget": parsed["budget"]
        },
        goto=next_node
    )


def search_travel_options(state: TravelPlan) -> dict:
    print(f"Searching for {state['destination']}...")
    return {"search_results": ["Flight $450", "Hotel $120/night"]}

def human_review(state: TravelPlan) -> Command:
    print("PAUSED — waiting for human input")
    return Command(goto=END)  # for now just end

def build_itinerary(state: TravelPlan) -> dict:
    return {"itinerary": ["Day 1: Eiffel Tower", "Day 2: Louvre"]}

def send_plan(state: TravelPlan) -> dict:
    print("📧 Plan sent to user!")
    return {}


from langgraph.graph import StateGraph, START

# Create the graph using YOUR state
workflow = StateGraph(TravelPlan)

# Add nodes (workers)
workflow.add_node("classify", classify_travel_request)
workflow.add_node("search", search_travel_options)      # we'll create this next
workflow.add_node("human_review", human_review)
workflow.add_node("build_itinerary", build_itinerary)
workflow.add_node("send_plan", send_plan)

# Only the essential edges (nodes decide the rest!)
workflow.add_edge(START, "classify")
workflow.add_edge("send_plan", END)

# Compile — NO checkpointer (exactly what you wanted)
from langgraph.checkpoint import MemorySaver
memory = MemorySaver()
app = workflow.compile.checkpointer(checkpointer=memory)

print("✅ Travel agent graph ready!")



# Run the agent
initial_state = {
    "user_request": "Help me plan a 5-day trip to Paris in June with budget 2500",
    "user_id": "user123"
}

result = app.invoke(initial_state)
print(result)



def classify_travel_request(state:TravelPlan)->Command:
    print(f"classifying request for user {state['user_id']}")
    

    parsed={
        "destination":"Paris",
        "dates":{"start":"2025-06-01","end":"2025-06-05"},
        "budget":2500
    }

    if not parsed["destination"] or not parsed["dates"]:
        next_node = "human_review"      # missing info → ask user
    else:
        next_node = "search"            # ready to search flights/hotels    

    return Command(
        update={
            "destination": parsed["destination"],
            "dates": parsed["dates"],
            "budget": parsed["budget"]
        },
        goto=next_node
    )